const menu = [
  {
    id: 1,
    title: 'Sonntag 8. Mai 2022',
    category: 'gottesdienst',
    time: 10,
    img: './images/item-1.jpg',
    desc: `Andreas Waldmann: "Eigenschaften des Reiches Gottes" `,
    url: 'https://www.youtube.com/watch?v=USmu8zC9-N8' ,
  },
  {
    id: 2,
    title: 'Samstag 23. April 2022',
    category: 'jugendgottesdienst',
    time: 18,
    img: './images/item-2.jpg',
    desc: `Jakob Trab & Jugendteam: "Wem bin ich wichtig?"`,
    url: 'https://www.youtube.com/watch?v=USmu8zC9-N8' ,
  },
  {
    id: 3,
    title: 'Royal Rangers Freitags',
    category: 'andere programme',
    time: 17,
    img: './images/item-3.jpg',
    desc: `Die Royal Rangers sind christliche Pfadfinder, die mit Gottes Hilfe und biblischen Werten eine gesunde, abenteuerliche Alternative zum mediengeprägten Alltag heutiger Kinder und Jugendlicher anbieten.`,
    url: 'https://www.youtube.com/watch?v=USmu8zC9-N8' ,
  },
  {
    id: 4,
    title: 'Sonntag 15. Mai 2022',
    category: 'gottesdienst',
    time: 10,
    img: './images/item-4.jpg',
    desc: `Vanessa Weise: " Die Brille Gottes"  (Live-Stream oder vor Ort)`,
    url: 'https://www.youtube.com/watch?v=USmu8zC9-N8' ,
  },
  {
    id: 5,
    title: 'Samstag 7. Mai 2022',
    category: 'jugendgottesdienst',
    time: 18,
    img: './images/item-8.jpg',
    desc: `Julian Wolff & das Jugendteam: "Jesus liebt dich, wie du bist"`,
    url: 'https://www.youtube.com/watch?v=sikjpMvEsu0' ,
  },
  {
    id: 6,
    title: 'Kleingruppen Donnerstags',
    category: 'andere programme',
    time: 17,
    img: './images/item-6.jpeg',
    desc: `Im ganzen Norden von Hamburg treffen sich Menschen aus der Gemeinde in einem privatem Rahmen in kleineren Gruppen.`,
    url: 'https://www.youtube.com/watch?v=USmu8zC9-N8' ,
  },
  {
    id: 7,
    title: 'Sonntag 22. Mai 2022',
    category: 'gottesdienst',
    time: 10,
    img: './images/item-7.jpg',
    desc: `Marion Ruchelka: "Vom Wachsen und Reifen"`,
    url: 'https://www.youtube.com/watch?v=USmu8zC9-N8' ,
  },
  {
    id: 8,
    title: 'Samstag 21. Mai 2022 ',
    category: 'jugendgottesdienst',
    time: 18,
    img: './images/item-5.jpg',
    desc: `Julian Wolff & das Jugendteam: "EIn Lagerfeuerabend mit Jesus" `,
    url: 'https://www.youtube.com/watch?v=cP_kXlBnHXo' ,
  },
  {
    id: 9,
    title: 'Ausflug 12. Juni 2022',
    category: 'andere programme',
    time: 11,
    img: './images/item-9.jpg',
    desc: `Am Sonntag treffen wir uns im Erlebniswald Trappenkamp.`,
    url: 'https://www.erlebniswald-trappenkamp.de/' ,
  },
];
export default menu;
